# Generated by Django 5.1.1 on 2025-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comites_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioaprendiz',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('OTRO', 'OTRO')], default='OTRO', max_length=255),
        ),
    ]
